# Generated by Django 4.0 on 2022-01-15 00:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0002_contact_us'),
    ]

    operations = [
        migrations.CreateModel(
            name='feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=20, null=True)),
                ('email', models.CharField(max_length=20, null=True)),
                ('mobile', models.CharField(max_length=50, null=True)),
                ('feedback', models.CharField(max_length=50, null=True)),
            ],
        ),
        migrations.RenameModel(
            old_name='Contact_us',
            new_name='Contact',
        ),
    ]
