# Generated by Django 4.0 on 2022-01-15 00:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0003_feedback_rename_contact_us_contact'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='feedback',
            new_name='ABCD',
        ),
    ]
