# Generated by Django 4.0 on 2022-01-15 00:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0004_rename_feedback_abcd'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ABCD',
            new_name='Feedback',
        ),
    ]
